openapi: 3.1.0
info:
  title: Superpower Ads Moderation API
  version: "0.0.1"
servers:
  - url: https://bold-wave-9be7.alan-2d6.workers.dev
paths:
  /:
    get:
      summary: Return public facts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fact'
components:
  schemas:
    Fact:
      type: object
      properties:
        fact:
          type: string
